name: pytest-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose -y

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for docker container to complete and report be available
      run: |
        for i in {1..30}; do
          if curl -f http://localhost:8000/report.html; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for the server to start..."
          sleep 2
        done

    - name: Test server if report is available
      run: curl -f http://localhost:8000/report.html

    - name: Copy test report to artifacts
      run: docker cp $(docker-compose ps -q pytest):/app/tests/report.html report.html

    - name: Upload test report to artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html

    - name: Stop and remove Docker Compose services
      run: docker-compose down
