name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose -y

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for server to start
      run: sleep 10

    - name: Test server
      run: curl -f http://localhost:8000/report.html

    - name: Copy test report
      run: docker cp $(docker-compose ps -q app):/app/tests/report.html report.html

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html

    - name: Stop and remove Docker Compose services
      run: docker-compose down
